require: rubocop-rspec

AllCops:
  DisplayCopNames: true
  DisplayStyleGuide: true
  EnabledByDefault: true
  ExtraDetails: true
  Exclude:
    - db/schema.rb

Layout/AlignParameters:
  EnforcedStyle: with_fixed_indentation

Layout/CaseIndentation:
  EnforcedStyle: end

Layout/ExtraSpacing:
  AllowForAlignment: false

Layout/FirstParameterIndentation:
  EnforcedStyle: consistent

Layout/IndentArray:
  EnforcedStyle: consistent

Layout/IndentHash:
  EnforcedStyle: consistent

Layout/MultilineAssignmentLayout:
  Enabled: false

Layout/MultilineMethodCallIndentation:
  EnforcedStyle: indented

Layout/MultilineMethodDefinitionBraceLayout:
  EnforcedStyle: new_line

Layout/MultilineOperationIndentation:
  EnforcedStyle: indented

Lint/EndAlignment:
  EnforcedStyleAlignWith: variable

Metrics/BlockLength:
  Exclude:
    - spec/**/*
    - config/routes.rb

Metrics/LineLength:
  Max: 100

Metrics/MethodLength:
  Max: 20

Rails/HasAndBelongsToMany:
  Enabled: false

Rails/SkipsModelValidations:
  Exclude:
    - db/migrate/**/*

RSpec/ImplicitExpect:
  EnforcedStyle: should

RSpec/ExampleLength:
  Max: 5

RSpec/LetSetup:
  Enabled: false

RSpec/MultipleExpectations:
  Max: 5

RSpec/NamedSubject:
  Enabled: false

RSpec/NestedGroups:
  Enabled: false

Style/BracesAroundHashParameters:
  Enabled: false

Style/ClassAndModuleChildren:
  Enabled: false

Style/Copyright:
  Enabled: false

Style/Documentation:
  Enabled: false

Style/DocumentationMethod:
  Enabled: false

Style/DoubleNegation:
  Enabled: false

Style/EmptyMethod:
  EnforcedStyle: expanded

Style/InlineComment:
  Enabled: false

Style/Lambda:
  EnforcedStyle: literal

Style/MethodCallWithArgsParentheses:
  Enabled: false

Style/MissingElse:
  Enabled: false

Style/ParallelAssignment:
  Enabled: false

Style/RegexpLiteral:
  EnforcedStyle: slashes
  AllowInnerSlashes: true

Style/SymbolArray:
  EnforcedStyle: brackets

Style/TrailingCommaInLiteral:
  EnforcedStyleForMultiline: comma

Style/YodaCondition:
  Enabled: false
